### ISSUE TITLE
Default plugin support

### ISSUE THREAD

**Issue by scottbedard** [scottbedard/vuetober-spa#1]
Eventually, I'd like this theme to support a few common plugins out of the box. The basic way I intend for this to work is to have branches that add support and basic pages for different plugins, and to keep these branches always in a state where they can be merged into your project.

So for example, to create a new theme that supports RainLab.User and RainLab.Blog, the installation would be as follows.

```bash
git clone git@github.com:scottbedard/vuetober-spa.git mytheme

cd mytheme

git merge rainlab-user

git merge rainlab-blog
```

**Comment by Teranode** [comment]
This repository provide's some great insight into user authentication and middlewares:

https://github.com/cretueusebiu/laravel-vue-spa/tree/master/resources/js

i've already integrated it into this project

**Comment by scottbedard** [comment]
That's awesome, I'd love to see what you've come up with! The pattern I generally use to interface with [RainLab.User](https://github.com/rainlab/user-plugin) is to use [GivingTeam.Auth](https://github.com/givingteam/oc-auth-plugin) to expose endpoints, and then using our [`beforeEach` navigation guard](https://github.com/givingteam/oc-auth-plugin/blob/master/Plugin.php) to check meta data about the route.

**Comment by Teranode** [comment]
Ill make a fork with the changes, at the same time i could use some help working with a plugin i made for vue regarding permissions https://gist.github.com/Teranode/864842c9f6b6aa60dfe0e4869462f2e1.

I use `Vue.use(Gate, { user: store.getters['user/user])` (the store is the problem). When I put this as a plugin and the plugin tries to get the store i get an error that the store isnt there ( im guessing that the Gate is loading before the store)
