### ISSUE TITLE
How publish that theme?

### ISSUE THREAD

**Issue by phpiando** [scottbedard/vuetober-spa#11]
Can I publish this theme using an Apache server like other themes?

And if I can, is there any extra configuration?
At this moment I did the "yarn build" and copied the entire folder but it is giving an error ...

```
Uncaught SyntaxError: Unexpected token '<'
app.2c1ba2d4.js:1 
Uncaught SyntaxError: Unexpected token '<'
```

**Comment by scottbedard** [comment]
I'll need more information to help you debug this, could you upload your repo somewhere so I can see what's in your app file?

**Comment by phpiando** [comment]
Hi @scottbedard  thanks for answers...

The repository was yours, I just used the "git clone", compiled the files using "yarn build" and put it on the server, however, I use an apache2 server with php7.2 and the theme didn't work.

And my question is can I use this theme using an apache + php server? or do i need to install october on a nodejs server?

**Comment by scottbedard** [comment]
It sounds like maybe your compiled files aren't making it to the server? Be aware that [built files are excluded from source control](https://github.com/scottbedard/vuetober-spa/blob/master/.gitignore#L3-L5), so if you're using git to transfer the files you'll need to either commit these, or build your production files on the server after pulling.

I just spun up a new Vuetober spa to verify that everything still works, and had no problems.

**Comment by phpiando** [comment]
@scottbedard  Hi thanks for support.. 
Well, come on, I put down the steps I did.
I did a git clone of the project as it is, and executed the commands you put in the README, only detail, I didn't use the command "yarn serves" because the server I'm using is apache with php, and this is my doubt, if this project runs in such an environment, anyway i put the rest of the steps below.

using: yarn build inside folder themes... 
https://prnt.sc/swnb8o

Server apache+php started:
https://prnt.sc/swnchu

Theme activated:
https://prnt.sc/swndco

Home page:
https://prnt.sc/swndv7

Code generate in yarn build in HTML:

```
<!DOCTYPE html>
<html>
   <head>
      <meta charset=utf-8>
      <meta content="IE=edge" http-equiv=X-UA-Compatible>
      <meta name=viewport content="width=device-width,initial-scale=1">
      <meta name=vuetober content="{&quot;env&quot;:&quot;development&quot;,&quot;token&quot;:&quot;6YNoZMfjb8kyxuWbAVQWMacAZH92EdkNiL1HZctp&quot;}">
      <title>vuetober</title>
      <link href=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/about.0b5bf7a1.js rel=prefetch>
      <link href=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/css/app.4aca9b2b.css rel=preload as=style>
      <link href=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/app.cd3d29fd.js rel=preload as=script>
      <link href=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/chunk-vendors.cd3df5b5.js rel=preload as=script>
      <link href=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/css/app.4aca9b2b.css rel=stylesheet>
   </head>
   <body>
      <noscript><strong>We're sorry but vuetober doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript>
      <div id=app></div>
      <script src=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/chunk-vendors.cd3df5b5.js></script><script src=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/app.cd3d29fd.js></script>
   </body>
</html>
```

**Comment by scottbedard** [comment]
Hmm, maybe you just need to specify a `baseUrl`? Try creating the following file...

```js
// vue.config.js
module.exports = {
  pluginOptions: {
    vuetober: {
      baseUrl: '/themes/your-theme/assets',
    },
  },
};
```

This basically just specifies where your assets directory lives, so instead of

```html
<script src=/C:\Projetos\backoffice-projects\themes\vuetober-spa\assets/js/chunk-vendors.cd3df5b5.js></script>
```

You'd end up with something like this

```html
<script src=/themes/your-theme/assets/js/chunk-vendors.cd3df5b5.js></script>
```

I recommend leaving this value `undefined` in development (if that was previously working), so something like this for your `baseUrl` might be more appropriate...

```js
const baseUrl = process.env.NODE_ENV === 'production'
  ? '/themes/your-theme/assets'
  : undefined
```

Also be aware, that to work in development mode you'll still need to run the `serve` command to re-compile assets when files change. The theme entry point is still served from PHP land, but your development assets will be served from a node server.

**Comment by phpiando** [comment]
Great!!!!!!!!!!!!!! Its work!!!!!!!!!!
Thanks @scottbedard 

I will continue the development now, thank you very much for the support.
