### ISSUE TITLE
Work with CSRF

### ISSUE THREAD

**Issue by Teranode** [scottbedard/vuetober-spa#3]
Hi I made a package that uses laravel's auth and is compatible with october, so i could use passport and what im wondering is how can i put the csrf token in an axios request like how laravel does?

https://github.com/laravel/laravel/blob/master/resources/js/bootstrap.js#L23
Package: https://github.com/Teranode/october-laravel-auth-bridge

**Comment by scottbedard** [comment]
The session token is already being included with the initial data in our `index.htm` file, adding something like this in the `main.js` file should get you the rest of the way.

```js
import axios from 'axios';

axios.interceptors.request.use((config) => {
    if (config.url.startsWith('/')) {
        return {
            ...config,
            headers: {
                ...config.headers,
                'X-CSRF-TOKEN': token,
            },
        };
    }

    return config;
});
```

This will include the token on all local requests, and we should probably include an initializer out of the box to handle data included on the initial page load. I'll try to get the implemented in the next few days.
