### ISSUE TITLE
DevServer on production server

### ISSUE THREAD

**Issue by Teranode** [scottbedard/vuetober-spa#4]
I'm running into a little issue with running `yarn serve` on a production server instead of my local computer. On my computer it works fine, but when I use the production server i cant get it to work.

The reason i want to to work is because it builds fine on both local and ps (production server) but the ps build has some incompatibility with js and css that only takes place there and not on the local server, so i want to debug it on the ps.

**Comment by scottbedard** [comment]
Hmm, I've never tried serving the dev assets from a production server before, but I don't see why that wouldn't work. What errors are you running into?

**Comment by Teranode** [comment]
since i cant work with the dev server, im just doing 'build --watch --mode=production
